// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace UI.Controllers
{
    public partial class StatisticsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected StatisticsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public StatisticsController Actions { get { return MVC.Statistics; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Statistics";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Statistics";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string AlbumStats = "AlbumStats";
            public readonly string BookStats = "BookStats";
            public readonly string GameStats = "GameStats";
            public readonly string MovieStats = "MovieStats";
            public readonly string PopStats = "PopStats";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string AlbumStats = "AlbumStats";
            public const string BookStats = "BookStats";
            public const string GameStats = "GameStats";
            public const string MovieStats = "MovieStats";
            public const string PopStats = "PopStats";
        }


        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AlbumStatsTable = "_AlbumStatsTable";
                public readonly string _BookStatsTable = "_BookStatsTable";
                public readonly string _GameStatsTable = "_GameStatsTable";
                public readonly string _MovieStatsTable = "_MovieStatsTable";
                public readonly string _PopStatsTable = "_PopStatsTable";
                public readonly string _StatsTable = "_StatsTable";
                public readonly string AlbumStats = "AlbumStats";
                public readonly string BookStats = "BookStats";
                public readonly string GameStats = "GameStats";
                public readonly string Index = "Index";
                public readonly string MovieStats = "MovieStats";
                public readonly string PopStats = "PopStats";
            }
            public readonly string _AlbumStatsTable = "~/Views/Statistics/_AlbumStatsTable.cshtml";
            public readonly string _BookStatsTable = "~/Views/Statistics/_BookStatsTable.cshtml";
            public readonly string _GameStatsTable = "~/Views/Statistics/_GameStatsTable.cshtml";
            public readonly string _MovieStatsTable = "~/Views/Statistics/_MovieStatsTable.cshtml";
            public readonly string _PopStatsTable = "~/Views/Statistics/_PopStatsTable.cshtml";
            public readonly string _StatsTable = "~/Views/Statistics/_StatsTable.cshtml";
            public readonly string AlbumStats = "~/Views/Statistics/AlbumStats.cshtml";
            public readonly string BookStats = "~/Views/Statistics/BookStats.cshtml";
            public readonly string GameStats = "~/Views/Statistics/GameStats.cshtml";
            public readonly string Index = "~/Views/Statistics/Index.cshtml";
            public readonly string MovieStats = "~/Views/Statistics/MovieStats.cshtml";
            public readonly string PopStats = "~/Views/Statistics/PopStats.cshtml";
            static readonly _ChartsClass s_Charts = new _ChartsClass();
            public _ChartsClass Charts { get { return s_Charts; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _ChartsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _AlbumFormatChart = "_AlbumFormatChart";
                    public readonly string _AlbumSpeedChart = "_AlbumSpeedChart";
                    public readonly string _AlbumTypeChart = "_AlbumTypeChart";
                    public readonly string _BookTypeChart = "_BookTypeChart";
                    public readonly string _CompletionStatusChart = "_CompletionStatusChart";
                    public readonly string _ConditionCharts = "_ConditionCharts";
                    public readonly string _CurrentGeneration = "_CurrentGeneration";
                    public readonly string _GameRatingChart = "_GameRatingChart";
                    public readonly string _GameTypeChart = "_GameTypeChart";
                    public readonly string _HandheldChart = "_HandheldChart";
                    public readonly string _ItemTypeChart = "_ItemTypeChart";
                    public readonly string _MediaTypesChart = "_MediaTypesChart";
                    public readonly string _MovieRatingChart = "_MovieRatingChart";
                    public readonly string _MovieTypeChart = "_MovieTypeChart";
                    public readonly string _NintendoChart = "_NintendoChart";
                    public readonly string _PlayStationChart = "_PlayStationChart";
                    public readonly string _XboxChart = "_XboxChart";
                }
                public readonly string _AlbumFormatChart = "~/Views/Statistics/Charts/_AlbumFormatChart.cshtml";
                public readonly string _AlbumSpeedChart = "~/Views/Statistics/Charts/_AlbumSpeedChart.cshtml";
                public readonly string _AlbumTypeChart = "~/Views/Statistics/Charts/_AlbumTypeChart.cshtml";
                public readonly string _BookTypeChart = "~/Views/Statistics/Charts/_BookTypeChart.cshtml";
                public readonly string _CompletionStatusChart = "~/Views/Statistics/Charts/_CompletionStatusChart.cshtml";
                public readonly string _ConditionCharts = "~/Views/Statistics/Charts/_ConditionCharts.cshtml";
                public readonly string _CurrentGeneration = "~/Views/Statistics/Charts/_CurrentGeneration.cshtml";
                public readonly string _GameRatingChart = "~/Views/Statistics/Charts/_GameRatingChart.cshtml";
                public readonly string _GameTypeChart = "~/Views/Statistics/Charts/_GameTypeChart.cshtml";
                public readonly string _HandheldChart = "~/Views/Statistics/Charts/_HandheldChart.cshtml";
                public readonly string _ItemTypeChart = "~/Views/Statistics/Charts/_ItemTypeChart.cshtml";
                public readonly string _MediaTypesChart = "~/Views/Statistics/Charts/_MediaTypesChart.cshtml";
                public readonly string _MovieRatingChart = "~/Views/Statistics/Charts/_MovieRatingChart.cshtml";
                public readonly string _MovieTypeChart = "~/Views/Statistics/Charts/_MovieTypeChart.cshtml";
                public readonly string _NintendoChart = "~/Views/Statistics/Charts/_NintendoChart.cshtml";
                public readonly string _PlayStationChart = "~/Views/Statistics/Charts/_PlayStationChart.cshtml";
                public readonly string _XboxChart = "~/Views/Statistics/Charts/_XboxChart.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_StatisticsController : UI.Controllers.StatisticsController
    {
        public T4MVC_StatisticsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AlbumStatsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult AlbumStats()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AlbumStats);
            AlbumStatsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void BookStatsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult BookStats()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BookStats);
            BookStatsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GameStatsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GameStats()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GameStats);
            GameStatsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MovieStatsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult MovieStats()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MovieStats);
            MovieStatsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PopStatsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PopStats()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PopStats);
            PopStatsOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
