// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static UI.Controllers.AccountController Account = new UI.Controllers.T4MVC_AccountController();
    public static UI.Controllers.AlbumController Album = new UI.Controllers.T4MVC_AlbumController();
    public static UI.Controllers.BookController Book = new UI.Controllers.T4MVC_BookController();
    public static UI.Controllers.ElmahController Elmah = new UI.Controllers.T4MVC_ElmahController();
    public static UI.Controllers.GameController Game = new UI.Controllers.T4MVC_GameController();
    public static UI.Controllers.HomeController Home = new UI.Controllers.T4MVC_HomeController();
    public static UI.Controllers.ManageController Manage = new UI.Controllers.T4MVC_ManageController();
    public static UI.Controllers.MovieController Movie = new UI.Controllers.T4MVC_MovieController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        public static readonly string bootbox_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootbox.min.js") ? Url("bootbox.min.js") : Url("bootbox.js");
        public static readonly string bootbox_min_js = Url("bootbox.min.js");
        public static readonly string bootbox_min_js_map = Url("bootbox.min.js.map");
        public static readonly string bootstrap_3_0_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-3.0.1.min.js") ? Url("bootstrap-3.0.1.min.js") : Url("bootstrap-3.0.1.js");
        public static readonly string bootstrap_3_0_1_min_js = Url("bootstrap-3.0.1.min.js");
        public static readonly string bootstrap_3_0_1_min_js_map = Url("bootstrap-3.0.1.min.js.map");
        public static readonly string bootstrap_datepicker_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-datepicker.min.js") ? Url("bootstrap-datepicker.min.js") : Url("bootstrap-datepicker.js");
        public static readonly string bootstrap_datepicker_min_js = Url("bootstrap-datepicker.min.js");
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Hydrogen {
            private const string URLPATH = "~/Scripts/Hydrogen";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
            public static readonly string jquery_easing_1_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.easing.1.3.min.js") ? Url("jquery.easing.1.3.min.js") : Url("jquery.easing.1.3.js");
            public static readonly string jquery_magnific_popup_min_js = Url("jquery.magnific-popup.min.js");
            public static readonly string jquery_min_js = Url("jquery.min.js");
            public static readonly string jquery_waypoints_min_js = Url("jquery.waypoints.min.js");
            public static readonly string main_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/main.min.js") ? Url("main.min.js") : Url("main.js");
            public static readonly string modernizr_2_6_2_min_js = Url("modernizr-2.6.2.min.js");
            public static readonly string respond_min_js = Url("respond.min.js");
            public static readonly string salvattore_min_js = Url("salvattore.min.js");
        }
    
        public static readonly string jquery_2_1_3_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-2.1.3.intellisense.min.js") ? Url("jquery-2.1.3.intellisense.min.js") : Url("jquery-2.1.3.intellisense.js");
        public static readonly string jquery_2_1_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-2.1.3.min.js") ? Url("jquery-2.1.3.min.js") : Url("jquery-2.1.3.js");
        public static readonly string jquery_2_1_3_min_js = Url("jquery-2.1.3.min.js");
        public static readonly string jquery_2_1_3_min_js_map = Url("jquery-2.1.3.min.js.map");
        public static readonly string jquery_2_2_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-2.2.1.min.js") ? Url("jquery-2.2.1.min.js") : Url("jquery-2.2.1.js");
        public static readonly string jquery_2_2_1_min_js = Url("jquery-2.2.1.min.js");
        public static readonly string jquery_2_2_1_min_map = Url("jquery-2.2.1.min.map");
        public static readonly string jquery_ui_1_11_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.11.2.min.js") ? Url("jquery-ui-1.11.2.min.js") : Url("jquery-ui-1.11.2.js");
        public static readonly string jquery_ui_1_11_2_min_js = Url("jquery-ui-1.11.2.min.js");
        public static readonly string jquery_ui_1_11_2_min_js_map = Url("jquery-ui-1.11.2.min.js.map");
        public static readonly string jquery_ui_1_11_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.11.3.min.js") ? Url("jquery-ui-1.11.3.min.js") : Url("jquery-ui-1.11.3.js");
        public static readonly string jquery_ui_1_11_3_min_js = Url("jquery-ui-1.11.3.min.js");
        public static readonly string jquery_ui_1_11_3_min_js_map = Url("jquery-ui-1.11.3.min.js.map");
        public static readonly string jquery_ui_1_11_4_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.11.4.min.js") ? Url("jquery-ui-1.11.4.min.js") : Url("jquery-ui-1.11.4.js");
        public static readonly string jquery_ui_1_11_4_min_js = Url("jquery-ui-1.11.4.min.js");
        public static readonly string jquery_mobile_1_4_5_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.mobile-1.4.5.min.js") ? Url("jquery.mobile-1.4.5.min.js") : Url("jquery.mobile-1.4.5.js");
        public static readonly string jquery_mobile_1_4_5_min_js = Url("jquery.mobile-1.4.5.min.js");
        public static readonly string jquery_mobile_1_4_5_min_map = Url("jquery.mobile-1.4.5.min.map");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_min_js_map = Url("jquery.validate.min.js.map");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class locales {
            private const string URLPATH = "~/Scripts/locales";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string bootstrap_datepicker_ar_min_js = Url("bootstrap-datepicker.ar.min.js");
            public static readonly string bootstrap_datepicker_az_min_js = Url("bootstrap-datepicker.az.min.js");
            public static readonly string bootstrap_datepicker_bg_min_js = Url("bootstrap-datepicker.bg.min.js");
            public static readonly string bootstrap_datepicker_bs_min_js = Url("bootstrap-datepicker.bs.min.js");
            public static readonly string bootstrap_datepicker_ca_min_js = Url("bootstrap-datepicker.ca.min.js");
            public static readonly string bootstrap_datepicker_cs_min_js = Url("bootstrap-datepicker.cs.min.js");
            public static readonly string bootstrap_datepicker_cy_min_js = Url("bootstrap-datepicker.cy.min.js");
            public static readonly string bootstrap_datepicker_da_min_js = Url("bootstrap-datepicker.da.min.js");
            public static readonly string bootstrap_datepicker_de_min_js = Url("bootstrap-datepicker.de.min.js");
            public static readonly string bootstrap_datepicker_el_min_js = Url("bootstrap-datepicker.el.min.js");
            public static readonly string bootstrap_datepicker_en_AU_min_js = Url("bootstrap-datepicker.en-AU.min.js");
            public static readonly string bootstrap_datepicker_en_GB_min_js = Url("bootstrap-datepicker.en-GB.min.js");
            public static readonly string bootstrap_datepicker_eo_min_js = Url("bootstrap-datepicker.eo.min.js");
            public static readonly string bootstrap_datepicker_es_min_js = Url("bootstrap-datepicker.es.min.js");
            public static readonly string bootstrap_datepicker_et_min_js = Url("bootstrap-datepicker.et.min.js");
            public static readonly string bootstrap_datepicker_eu_min_js = Url("bootstrap-datepicker.eu.min.js");
            public static readonly string bootstrap_datepicker_fa_min_js = Url("bootstrap-datepicker.fa.min.js");
            public static readonly string bootstrap_datepicker_fi_min_js = Url("bootstrap-datepicker.fi.min.js");
            public static readonly string bootstrap_datepicker_fo_min_js = Url("bootstrap-datepicker.fo.min.js");
            public static readonly string bootstrap_datepicker_fr_CH_min_js = Url("bootstrap-datepicker.fr-CH.min.js");
            public static readonly string bootstrap_datepicker_fr_min_js = Url("bootstrap-datepicker.fr.min.js");
            public static readonly string bootstrap_datepicker_gl_min_js = Url("bootstrap-datepicker.gl.min.js");
            public static readonly string bootstrap_datepicker_he_min_js = Url("bootstrap-datepicker.he.min.js");
            public static readonly string bootstrap_datepicker_hr_min_js = Url("bootstrap-datepicker.hr.min.js");
            public static readonly string bootstrap_datepicker_hu_min_js = Url("bootstrap-datepicker.hu.min.js");
            public static readonly string bootstrap_datepicker_hy_min_js = Url("bootstrap-datepicker.hy.min.js");
            public static readonly string bootstrap_datepicker_id_min_js = Url("bootstrap-datepicker.id.min.js");
            public static readonly string bootstrap_datepicker_is_min_js = Url("bootstrap-datepicker.is.min.js");
            public static readonly string bootstrap_datepicker_it_CH_min_js = Url("bootstrap-datepicker.it-CH.min.js");
            public static readonly string bootstrap_datepicker_it_min_js = Url("bootstrap-datepicker.it.min.js");
            public static readonly string bootstrap_datepicker_ja_min_js = Url("bootstrap-datepicker.ja.min.js");
            public static readonly string bootstrap_datepicker_ka_min_js = Url("bootstrap-datepicker.ka.min.js");
            public static readonly string bootstrap_datepicker_kh_min_js = Url("bootstrap-datepicker.kh.min.js");
            public static readonly string bootstrap_datepicker_kk_min_js = Url("bootstrap-datepicker.kk.min.js");
            public static readonly string bootstrap_datepicker_ko_min_js = Url("bootstrap-datepicker.ko.min.js");
            public static readonly string bootstrap_datepicker_kr_min_js = Url("bootstrap-datepicker.kr.min.js");
            public static readonly string bootstrap_datepicker_lt_min_js = Url("bootstrap-datepicker.lt.min.js");
            public static readonly string bootstrap_datepicker_lv_min_js = Url("bootstrap-datepicker.lv.min.js");
            public static readonly string bootstrap_datepicker_me_min_js = Url("bootstrap-datepicker.me.min.js");
            public static readonly string bootstrap_datepicker_mk_min_js = Url("bootstrap-datepicker.mk.min.js");
            public static readonly string bootstrap_datepicker_mn_min_js = Url("bootstrap-datepicker.mn.min.js");
            public static readonly string bootstrap_datepicker_ms_min_js = Url("bootstrap-datepicker.ms.min.js");
            public static readonly string bootstrap_datepicker_nb_min_js = Url("bootstrap-datepicker.nb.min.js");
            public static readonly string bootstrap_datepicker_nl_BE_min_js = Url("bootstrap-datepicker.nl-BE.min.js");
            public static readonly string bootstrap_datepicker_nl_min_js = Url("bootstrap-datepicker.nl.min.js");
            public static readonly string bootstrap_datepicker_no_min_js = Url("bootstrap-datepicker.no.min.js");
            public static readonly string bootstrap_datepicker_pl_min_js = Url("bootstrap-datepicker.pl.min.js");
            public static readonly string bootstrap_datepicker_pt_BR_min_js = Url("bootstrap-datepicker.pt-BR.min.js");
            public static readonly string bootstrap_datepicker_pt_min_js = Url("bootstrap-datepicker.pt.min.js");
            public static readonly string bootstrap_datepicker_ro_min_js = Url("bootstrap-datepicker.ro.min.js");
            public static readonly string bootstrap_datepicker_rs_latin_min_js = Url("bootstrap-datepicker.rs-latin.min.js");
            public static readonly string bootstrap_datepicker_rs_min_js = Url("bootstrap-datepicker.rs.min.js");
            public static readonly string bootstrap_datepicker_ru_min_js = Url("bootstrap-datepicker.ru.min.js");
            public static readonly string bootstrap_datepicker_sk_min_js = Url("bootstrap-datepicker.sk.min.js");
            public static readonly string bootstrap_datepicker_sl_min_js = Url("bootstrap-datepicker.sl.min.js");
            public static readonly string bootstrap_datepicker_sq_min_js = Url("bootstrap-datepicker.sq.min.js");
            public static readonly string bootstrap_datepicker_sr_latin_min_js = Url("bootstrap-datepicker.sr-latin.min.js");
            public static readonly string bootstrap_datepicker_sr_min_js = Url("bootstrap-datepicker.sr.min.js");
            public static readonly string bootstrap_datepicker_sv_min_js = Url("bootstrap-datepicker.sv.min.js");
            public static readonly string bootstrap_datepicker_sw_min_js = Url("bootstrap-datepicker.sw.min.js");
            public static readonly string bootstrap_datepicker_th_min_js = Url("bootstrap-datepicker.th.min.js");
            public static readonly string bootstrap_datepicker_tr_min_js = Url("bootstrap-datepicker.tr.min.js");
            public static readonly string bootstrap_datepicker_uk_min_js = Url("bootstrap-datepicker.uk.min.js");
            public static readonly string bootstrap_datepicker_vi_min_js = Url("bootstrap-datepicker.vi.min.js");
            public static readonly string bootstrap_datepicker_zh_CN_min_js = Url("bootstrap-datepicker.zh-CN.min.js");
            public static readonly string bootstrap_datepicker_zh_TW_min_js = Url("bootstrap-datepicker.zh-TW.min.js");
        }
    
        public static readonly string modernizr_2_6_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.6.2.min.js") ? Url("modernizr-2.6.2.min.js") : Url("modernizr-2.6.2.js");
        public static readonly string modernizr_2_7_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.7.2.min.js") ? Url("modernizr-2.7.2.min.js") : Url("modernizr-2.7.2.js");
        public static readonly string modernizr_2_8_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.8.3.min.js") ? Url("modernizr-2.8.3.min.js") : Url("modernizr-2.8.3.js");
        public static readonly string Namespace_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Namespace.min.js") ? Url("Namespace.min.js") : Url("Namespace.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class PageSpecific {
            private const string URLPATH = "~/Scripts/PageSpecific";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        }
    
        public static readonly string respond_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/respond.min.js") ? Url("respond.min.js") : Url("respond.js");
        public static readonly string respond_matchmedia_addListener_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/respond.matchmedia.addListener.min.js") ? Url("respond.matchmedia.addListener.min.js") : Url("respond.matchmedia.addListener.js");
        public static readonly string respond_matchmedia_addListener_min_js = Url("respond.matchmedia.addListener.min.js");
        public static readonly string respond_matchmedia_addListener_min_js_map = Url("respond.matchmedia.addListener.min.js.map");
        public static readonly string respond_min_js = Url("respond.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Shared {
            private const string URLPATH = "~/Scripts/Shared";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _Layout_coffee = Url("_Layout.coffee");
            public static readonly string _Layout_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/_Layout.min.js") ? Url("_Layout.min.js") : Url("_Layout.js");
            public static readonly string Logout_coffee = Url("Logout.coffee");
            public static readonly string Logout_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Logout.min.js") ? Url("Logout.min.js") : Url("Logout.js");
            public static readonly string Logout_js_map = Url("Logout.js.map");
            public static readonly string Logout_min_js = Url("Logout.min.js");
            public static readonly string Logout_min_js_map = Url("Logout.min.js.map");
        }
    
        public static readonly string toastr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/toastr.min.js") ? Url("toastr.min.js") : Url("toastr.js");
        public static readonly string toastr_min_js = Url("toastr.min.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string bootstrap_datepicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-datepicker.min.css") ? Url("bootstrap-datepicker.min.css") : Url("bootstrap-datepicker.css");
        public static readonly string bootstrap_datepicker_css_map = Url("bootstrap-datepicker.css.map");
        public static readonly string bootstrap_datepicker_min_css = Url("bootstrap-datepicker.min.css");
        public static readonly string bootstrap_datepicker_min_css_map = Url("bootstrap-datepicker.min.css.map");
        public static readonly string bootstrap_datepicker_standalone_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-datepicker.standalone.min.css") ? Url("bootstrap-datepicker.standalone.min.css") : Url("bootstrap-datepicker.standalone.css");
        public static readonly string bootstrap_datepicker_standalone_css_map = Url("bootstrap-datepicker.standalone.css.map");
        public static readonly string bootstrap_datepicker_standalone_min_css = Url("bootstrap-datepicker.standalone.min.css");
        public static readonly string bootstrap_datepicker_standalone_min_css_map = Url("bootstrap-datepicker.standalone.min.css.map");
        public static readonly string bootstrap_datepicker3_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-datepicker3.min.css") ? Url("bootstrap-datepicker3.min.css") : Url("bootstrap-datepicker3.css");
        public static readonly string bootstrap_datepicker3_css_map = Url("bootstrap-datepicker3.css.map");
        public static readonly string bootstrap_datepicker3_min_css = Url("bootstrap-datepicker3.min.css");
        public static readonly string bootstrap_datepicker3_min_css_map = Url("bootstrap-datepicker3.min.css.map");
        public static readonly string bootstrap_datepicker3_standalone_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-datepicker3.standalone.min.css") ? Url("bootstrap-datepicker3.standalone.min.css") : Url("bootstrap-datepicker3.standalone.css");
        public static readonly string bootstrap_datepicker3_standalone_css_map = Url("bootstrap-datepicker3.standalone.css.map");
        public static readonly string bootstrap_datepicker3_standalone_min_css = Url("bootstrap-datepicker3.standalone.min.css");
        public static readonly string bootstrap_datepicker3_standalone_min_css_map = Url("bootstrap-datepicker3.standalone.min.css.map");
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
        public static readonly string bootstrap_css_map = Url("bootstrap.css.map");
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        public static readonly string bootstrap_min_css_map = Url("bootstrap.min.css.map");
        public static readonly string font_awesome_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/font-awesome.min.css") ? Url("font-awesome.min.css") : Url("font-awesome.css");
        public static readonly string font_awesome_min_css = Url("font-awesome.min.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Images {
            private const string URLPATH = "~/Content/Images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string ajax_loader_gif = Url("ajax-loader.gif");
            public static readonly string Book_jpg = Url("Book.jpg");
            public static readonly string Game_jpg = Url("Game.jpg");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class icons_png {
                private const string URLPATH = "~/Content/Images/icons-png";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string action_black_png = Url("action-black.png");
                public static readonly string action_white_png = Url("action-white.png");
                public static readonly string alert_black_png = Url("alert-black.png");
                public static readonly string alert_white_png = Url("alert-white.png");
                public static readonly string arrow_d_black_png = Url("arrow-d-black.png");
                public static readonly string arrow_d_l_black_png = Url("arrow-d-l-black.png");
                public static readonly string arrow_d_l_white_png = Url("arrow-d-l-white.png");
                public static readonly string arrow_d_r_black_png = Url("arrow-d-r-black.png");
                public static readonly string arrow_d_r_white_png = Url("arrow-d-r-white.png");
                public static readonly string arrow_d_white_png = Url("arrow-d-white.png");
                public static readonly string arrow_l_black_png = Url("arrow-l-black.png");
                public static readonly string arrow_l_white_png = Url("arrow-l-white.png");
                public static readonly string arrow_r_black_png = Url("arrow-r-black.png");
                public static readonly string arrow_r_white_png = Url("arrow-r-white.png");
                public static readonly string arrow_u_black_png = Url("arrow-u-black.png");
                public static readonly string arrow_u_l_black_png = Url("arrow-u-l-black.png");
                public static readonly string arrow_u_l_white_png = Url("arrow-u-l-white.png");
                public static readonly string arrow_u_r_black_png = Url("arrow-u-r-black.png");
                public static readonly string arrow_u_r_white_png = Url("arrow-u-r-white.png");
                public static readonly string arrow_u_white_png = Url("arrow-u-white.png");
                public static readonly string audio_black_png = Url("audio-black.png");
                public static readonly string audio_white_png = Url("audio-white.png");
                public static readonly string back_black_png = Url("back-black.png");
                public static readonly string back_white_png = Url("back-white.png");
                public static readonly string bars_black_png = Url("bars-black.png");
                public static readonly string bars_white_png = Url("bars-white.png");
                public static readonly string bullets_black_png = Url("bullets-black.png");
                public static readonly string bullets_white_png = Url("bullets-white.png");
                public static readonly string calendar_black_png = Url("calendar-black.png");
                public static readonly string calendar_white_png = Url("calendar-white.png");
                public static readonly string camera_black_png = Url("camera-black.png");
                public static readonly string camera_white_png = Url("camera-white.png");
                public static readonly string carat_d_black_png = Url("carat-d-black.png");
                public static readonly string carat_d_white_png = Url("carat-d-white.png");
                public static readonly string carat_l_black_png = Url("carat-l-black.png");
                public static readonly string carat_l_white_png = Url("carat-l-white.png");
                public static readonly string carat_r_black_png = Url("carat-r-black.png");
                public static readonly string carat_r_white_png = Url("carat-r-white.png");
                public static readonly string carat_u_black_png = Url("carat-u-black.png");
                public static readonly string carat_u_white_png = Url("carat-u-white.png");
                public static readonly string check_black_png = Url("check-black.png");
                public static readonly string check_white_png = Url("check-white.png");
                public static readonly string clock_black_png = Url("clock-black.png");
                public static readonly string clock_white_png = Url("clock-white.png");
                public static readonly string cloud_black_png = Url("cloud-black.png");
                public static readonly string cloud_white_png = Url("cloud-white.png");
                public static readonly string comment_black_png = Url("comment-black.png");
                public static readonly string comment_white_png = Url("comment-white.png");
                public static readonly string delete_black_png = Url("delete-black.png");
                public static readonly string delete_white_png = Url("delete-white.png");
                public static readonly string edit_black_png = Url("edit-black.png");
                public static readonly string edit_white_png = Url("edit-white.png");
                public static readonly string eye_black_png = Url("eye-black.png");
                public static readonly string eye_white_png = Url("eye-white.png");
                public static readonly string forbidden_black_png = Url("forbidden-black.png");
                public static readonly string forbidden_white_png = Url("forbidden-white.png");
                public static readonly string forward_black_png = Url("forward-black.png");
                public static readonly string forward_white_png = Url("forward-white.png");
                public static readonly string gear_black_png = Url("gear-black.png");
                public static readonly string gear_white_png = Url("gear-white.png");
                public static readonly string grid_black_png = Url("grid-black.png");
                public static readonly string grid_white_png = Url("grid-white.png");
                public static readonly string heart_black_png = Url("heart-black.png");
                public static readonly string heart_white_png = Url("heart-white.png");
                public static readonly string home_black_png = Url("home-black.png");
                public static readonly string home_white_png = Url("home-white.png");
                public static readonly string info_black_png = Url("info-black.png");
                public static readonly string info_white_png = Url("info-white.png");
                public static readonly string location_black_png = Url("location-black.png");
                public static readonly string location_white_png = Url("location-white.png");
                public static readonly string lock_black_png = Url("lock-black.png");
                public static readonly string lock_white_png = Url("lock-white.png");
                public static readonly string mail_black_png = Url("mail-black.png");
                public static readonly string mail_white_png = Url("mail-white.png");
                public static readonly string minus_black_png = Url("minus-black.png");
                public static readonly string minus_white_png = Url("minus-white.png");
                public static readonly string navigation_black_png = Url("navigation-black.png");
                public static readonly string navigation_white_png = Url("navigation-white.png");
                public static readonly string phone_black_png = Url("phone-black.png");
                public static readonly string phone_white_png = Url("phone-white.png");
                public static readonly string plus_black_png = Url("plus-black.png");
                public static readonly string plus_white_png = Url("plus-white.png");
                public static readonly string power_black_png = Url("power-black.png");
                public static readonly string power_white_png = Url("power-white.png");
                public static readonly string recycle_black_png = Url("recycle-black.png");
                public static readonly string recycle_white_png = Url("recycle-white.png");
                public static readonly string refresh_black_png = Url("refresh-black.png");
                public static readonly string refresh_white_png = Url("refresh-white.png");
                public static readonly string search_black_png = Url("search-black.png");
                public static readonly string search_white_png = Url("search-white.png");
                public static readonly string shop_black_png = Url("shop-black.png");
                public static readonly string shop_white_png = Url("shop-white.png");
                public static readonly string star_black_png = Url("star-black.png");
                public static readonly string star_white_png = Url("star-white.png");
                public static readonly string tag_black_png = Url("tag-black.png");
                public static readonly string tag_white_png = Url("tag-white.png");
                public static readonly string user_black_png = Url("user-black.png");
                public static readonly string user_white_png = Url("user-white.png");
                public static readonly string video_black_png = Url("video-black.png");
                public static readonly string video_white_png = Url("video-white.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class icons_svg {
                private const string URLPATH = "~/Content/Images/icons-svg";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string action_black_svg = Url("action-black.svg");
                public static readonly string action_white_svg = Url("action-white.svg");
                public static readonly string alert_black_svg = Url("alert-black.svg");
                public static readonly string alert_white_svg = Url("alert-white.svg");
                public static readonly string arrow_d_black_svg = Url("arrow-d-black.svg");
                public static readonly string arrow_d_l_black_svg = Url("arrow-d-l-black.svg");
                public static readonly string arrow_d_l_white_svg = Url("arrow-d-l-white.svg");
                public static readonly string arrow_d_r_black_svg = Url("arrow-d-r-black.svg");
                public static readonly string arrow_d_r_white_svg = Url("arrow-d-r-white.svg");
                public static readonly string arrow_d_white_svg = Url("arrow-d-white.svg");
                public static readonly string arrow_l_black_svg = Url("arrow-l-black.svg");
                public static readonly string arrow_l_white_svg = Url("arrow-l-white.svg");
                public static readonly string arrow_r_black_svg = Url("arrow-r-black.svg");
                public static readonly string arrow_r_white_svg = Url("arrow-r-white.svg");
                public static readonly string arrow_u_black_svg = Url("arrow-u-black.svg");
                public static readonly string arrow_u_l_black_svg = Url("arrow-u-l-black.svg");
                public static readonly string arrow_u_l_white_svg = Url("arrow-u-l-white.svg");
                public static readonly string arrow_u_r_black_svg = Url("arrow-u-r-black.svg");
                public static readonly string arrow_u_r_white_svg = Url("arrow-u-r-white.svg");
                public static readonly string arrow_u_white_svg = Url("arrow-u-white.svg");
                public static readonly string audio_black_svg = Url("audio-black.svg");
                public static readonly string audio_white_svg = Url("audio-white.svg");
                public static readonly string back_black_svg = Url("back-black.svg");
                public static readonly string back_white_svg = Url("back-white.svg");
                public static readonly string bars_black_svg = Url("bars-black.svg");
                public static readonly string bars_white_svg = Url("bars-white.svg");
                public static readonly string bullets_black_svg = Url("bullets-black.svg");
                public static readonly string bullets_white_svg = Url("bullets-white.svg");
                public static readonly string calendar_black_svg = Url("calendar-black.svg");
                public static readonly string calendar_white_svg = Url("calendar-white.svg");
                public static readonly string camera_black_svg = Url("camera-black.svg");
                public static readonly string camera_white_svg = Url("camera-white.svg");
                public static readonly string carat_d_black_svg = Url("carat-d-black.svg");
                public static readonly string carat_d_white_svg = Url("carat-d-white.svg");
                public static readonly string carat_l_black_svg = Url("carat-l-black.svg");
                public static readonly string carat_l_white_svg = Url("carat-l-white.svg");
                public static readonly string carat_r_black_svg = Url("carat-r-black.svg");
                public static readonly string carat_r_white_svg = Url("carat-r-white.svg");
                public static readonly string carat_u_black_svg = Url("carat-u-black.svg");
                public static readonly string carat_u_white_svg = Url("carat-u-white.svg");
                public static readonly string check_black_svg = Url("check-black.svg");
                public static readonly string check_white_svg = Url("check-white.svg");
                public static readonly string clock_black_svg = Url("clock-black.svg");
                public static readonly string clock_white_svg = Url("clock-white.svg");
                public static readonly string cloud_black_svg = Url("cloud-black.svg");
                public static readonly string cloud_white_svg = Url("cloud-white.svg");
                public static readonly string comment_black_svg = Url("comment-black.svg");
                public static readonly string comment_white_svg = Url("comment-white.svg");
                public static readonly string delete_black_svg = Url("delete-black.svg");
                public static readonly string delete_white_svg = Url("delete-white.svg");
                public static readonly string edit_black_svg = Url("edit-black.svg");
                public static readonly string edit_white_svg = Url("edit-white.svg");
                public static readonly string eye_black_svg = Url("eye-black.svg");
                public static readonly string eye_white_svg = Url("eye-white.svg");
                public static readonly string forbidden_black_svg = Url("forbidden-black.svg");
                public static readonly string forbidden_white_svg = Url("forbidden-white.svg");
                public static readonly string forward_black_svg = Url("forward-black.svg");
                public static readonly string forward_white_svg = Url("forward-white.svg");
                public static readonly string gear_black_svg = Url("gear-black.svg");
                public static readonly string gear_white_svg = Url("gear-white.svg");
                public static readonly string grid_black_svg = Url("grid-black.svg");
                public static readonly string grid_white_svg = Url("grid-white.svg");
                public static readonly string heart_black_svg = Url("heart-black.svg");
                public static readonly string heart_white_svg = Url("heart-white.svg");
                public static readonly string home_black_svg = Url("home-black.svg");
                public static readonly string home_white_svg = Url("home-white.svg");
                public static readonly string info_black_svg = Url("info-black.svg");
                public static readonly string info_white_svg = Url("info-white.svg");
                public static readonly string location_black_svg = Url("location-black.svg");
                public static readonly string location_white_svg = Url("location-white.svg");
                public static readonly string lock_black_svg = Url("lock-black.svg");
                public static readonly string lock_white_svg = Url("lock-white.svg");
                public static readonly string mail_black_svg = Url("mail-black.svg");
                public static readonly string mail_white_svg = Url("mail-white.svg");
                public static readonly string minus_black_svg = Url("minus-black.svg");
                public static readonly string minus_white_svg = Url("minus-white.svg");
                public static readonly string navigation_black_svg = Url("navigation-black.svg");
                public static readonly string navigation_white_svg = Url("navigation-white.svg");
                public static readonly string phone_black_svg = Url("phone-black.svg");
                public static readonly string phone_white_svg = Url("phone-white.svg");
                public static readonly string plus_black_svg = Url("plus-black.svg");
                public static readonly string plus_white_svg = Url("plus-white.svg");
                public static readonly string power_black_svg = Url("power-black.svg");
                public static readonly string power_white_svg = Url("power-white.svg");
                public static readonly string recycle_black_svg = Url("recycle-black.svg");
                public static readonly string recycle_white_svg = Url("recycle-white.svg");
                public static readonly string refresh_black_svg = Url("refresh-black.svg");
                public static readonly string refresh_white_svg = Url("refresh-white.svg");
                public static readonly string search_black_svg = Url("search-black.svg");
                public static readonly string search_white_svg = Url("search-white.svg");
                public static readonly string shop_black_svg = Url("shop-black.svg");
                public static readonly string shop_white_svg = Url("shop-white.svg");
                public static readonly string star_black_svg = Url("star-black.svg");
                public static readonly string star_white_svg = Url("star-white.svg");
                public static readonly string tag_black_svg = Url("tag-black.svg");
                public static readonly string tag_white_svg = Url("tag-white.svg");
                public static readonly string user_black_svg = Url("user-black.svg");
                public static readonly string user_white_svg = Url("user-white.svg");
                public static readonly string video_black_svg = Url("video-black.svg");
                public static readonly string video_white_svg = Url("video-white.svg");
            }
        
            public static readonly string Reel_jpg = Url("Reel.jpg");
            public static readonly string tmdb_logo_png = Url("tmdb-logo.png");
            public static readonly string Turntable_jpg = Url("Turntable.jpg");
            public static readonly string Turntable2_jpg = Url("Turntable2.jpg");
        }
    
        public static readonly string jquery_mobile_1_4_5_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.mobile-1.4.5.min.css") ? Url("jquery.mobile-1.4.5.min.css") : Url("jquery.mobile-1.4.5.css");
        public static readonly string jquery_mobile_1_4_5_min_css = Url("jquery.mobile-1.4.5.min.css");
        public static readonly string jquery_mobile_external_png_1_4_5_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.mobile.external-png-1.4.5.min.css") ? Url("jquery.mobile.external-png-1.4.5.min.css") : Url("jquery.mobile.external-png-1.4.5.css");
        public static readonly string jquery_mobile_external_png_1_4_5_min_css = Url("jquery.mobile.external-png-1.4.5.min.css");
        public static readonly string jquery_mobile_icons_1_4_5_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.mobile.icons-1.4.5.min.css") ? Url("jquery.mobile.icons-1.4.5.min.css") : Url("jquery.mobile.icons-1.4.5.css");
        public static readonly string jquery_mobile_icons_1_4_5_min_css = Url("jquery.mobile.icons-1.4.5.min.css");
        public static readonly string jquery_mobile_inline_png_1_4_5_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.mobile.inline-png-1.4.5.min.css") ? Url("jquery.mobile.inline-png-1.4.5.min.css") : Url("jquery.mobile.inline-png-1.4.5.css");
        public static readonly string jquery_mobile_inline_png_1_4_5_min_css = Url("jquery.mobile.inline-png-1.4.5.min.css");
        public static readonly string jquery_mobile_inline_svg_1_4_5_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.mobile.inline-svg-1.4.5.min.css") ? Url("jquery.mobile.inline-svg-1.4.5.min.css") : Url("jquery.mobile.inline-svg-1.4.5.css");
        public static readonly string jquery_mobile_inline_svg_1_4_5_min_css = Url("jquery.mobile.inline-svg-1.4.5.min.css");
        public static readonly string jquery_mobile_structure_1_4_5_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.mobile.structure-1.4.5.min.css") ? Url("jquery.mobile.structure-1.4.5.min.css") : Url("jquery.mobile.structure-1.4.5.css");
        public static readonly string jquery_mobile_structure_1_4_5_min_css = Url("jquery.mobile.structure-1.4.5.min.css");
        public static readonly string jquery_mobile_theme_1_4_5_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.mobile.theme-1.4.5.min.css") ? Url("jquery.mobile.theme-1.4.5.min.css") : Url("jquery.mobile.theme-1.4.5.css");
        public static readonly string jquery_mobile_theme_1_4_5_min_css = Url("jquery.mobile.theme-1.4.5.min.css");
        public static readonly string Responsive_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Responsive.min.css") ? Url("Responsive.min.css") : Url("Responsive.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Sass {
            private const string URLPATH = "~/Content/Sass";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string Main_scss = Url("Main.scss");
            public static readonly string Main_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Main.min.css") ? Url("Main.min.css") : Url("Main.css");
            public static readonly string Main_min_css = Url("Main.min.css");
        }
    
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class themes {
            private const string URLPATH = "~/Content/themes";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class @base {
                private const string URLPATH = "~/Content/themes/base";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string accordion_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/accordion.min.css") ? Url("accordion.min.css") : Url("accordion.css");
                public static readonly string all_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/all.min.css") ? Url("all.min.css") : Url("all.css");
                public static readonly string autocomplete_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/autocomplete.min.css") ? Url("autocomplete.min.css") : Url("autocomplete.css");
                public static readonly string base_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/base.min.css") ? Url("base.min.css") : Url("base.css");
                public static readonly string button_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/button.min.css") ? Url("button.min.css") : Url("button.css");
                public static readonly string core_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/core.min.css") ? Url("core.min.css") : Url("core.css");
                public static readonly string datepicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/datepicker.min.css") ? Url("datepicker.min.css") : Url("datepicker.css");
                public static readonly string dialog_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dialog.min.css") ? Url("dialog.min.css") : Url("dialog.css");
                public static readonly string draggable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/draggable.min.css") ? Url("draggable.min.css") : Url("draggable.css");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/Content/themes/base/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                    public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                    public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                    public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                    public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                    public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                    public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                    public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                    public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                    public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                    public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                    public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                    public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                }
            
                public static readonly string menu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/menu.min.css") ? Url("menu.min.css") : Url("menu.css");
                public static readonly string progressbar_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/progressbar.min.css") ? Url("progressbar.min.css") : Url("progressbar.css");
                public static readonly string resizable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/resizable.min.css") ? Url("resizable.min.css") : Url("resizable.css");
                public static readonly string selectable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/selectable.min.css") ? Url("selectable.min.css") : Url("selectable.css");
                public static readonly string selectmenu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/selectmenu.min.css") ? Url("selectmenu.min.css") : Url("selectmenu.css");
                public static readonly string slider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/slider.min.css") ? Url("slider.min.css") : Url("slider.css");
                public static readonly string sortable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/sortable.min.css") ? Url("sortable.min.css") : Url("sortable.css");
                public static readonly string spinner_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/spinner.min.css") ? Url("spinner.min.css") : Url("spinner.css");
                public static readonly string tabs_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/tabs.min.css") ? Url("tabs.min.css") : Url("tabs.css");
                public static readonly string theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/theme.min.css") ? Url("theme.min.css") : Url("theme.css");
                public static readonly string tooltip_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/tooltip.min.css") ? Url("tooltip.min.css") : Url("tooltip.css");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Hydrogen {
                private const string URLPATH = "~/Content/themes/Hydrogen";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string animate_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/animate.min.css") ? Url("animate.min.css") : Url("animate.css");
                public static readonly string icomoon_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/icomoon.min.css") ? Url("icomoon.min.css") : Url("icomoon.css");
                public static readonly string magnific_popup_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/magnific-popup.min.css") ? Url("magnific-popup.min.css") : Url("magnific-popup.css");
                public static readonly string salvattore_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/salvattore.min.css") ? Url("salvattore.min.css") : Url("salvattore.css");
                public static readonly string style_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/style.min.css") ? Url("style.min.css") : Url("style.css");
            }
        
        }
    
        public static readonly string toastr_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/toastr.min.css") ? Url("toastr.min.css") : Url("toastr.css");
        public static readonly string toastr_less = Url("toastr.less");
        public static readonly string toastr_min_css = Url("toastr.min.css");
        public static readonly string toastr_scss = Url("toastr.scss");
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static partial class Hydrogen 
            {
                public static class Assets
                {
                    public const string bootstrap_min_js = "~/Scripts/Hydrogen/bootstrap.min.js"; 
                    public const string jquery_easing_1_3_js = "~/Scripts/Hydrogen/jquery.easing.1.3.js"; 
                    public const string jquery_magnific_popup_min_js = "~/Scripts/Hydrogen/jquery.magnific-popup.min.js"; 
                    public const string jquery_min_js = "~/Scripts/Hydrogen/jquery.min.js"; 
                    public const string jquery_waypoints_min_js = "~/Scripts/Hydrogen/jquery.waypoints.min.js"; 
                    public const string main_js = "~/Scripts/Hydrogen/main.js"; 
                    public const string modernizr_2_6_2_min_js = "~/Scripts/Hydrogen/modernizr-2.6.2.min.js"; 
                    public const string respond_min_js = "~/Scripts/Hydrogen/respond.min.js"; 
                    public const string salvattore_min_js = "~/Scripts/Hydrogen/salvattore.min.js"; 
                }
            }
            public static partial class locales 
            {
                public static class Assets
                {
                    public const string bootstrap_datepicker_ar_min_js = "~/Scripts/locales/bootstrap-datepicker.ar.min.js"; 
                    public const string bootstrap_datepicker_az_min_js = "~/Scripts/locales/bootstrap-datepicker.az.min.js"; 
                    public const string bootstrap_datepicker_bg_min_js = "~/Scripts/locales/bootstrap-datepicker.bg.min.js"; 
                    public const string bootstrap_datepicker_bs_min_js = "~/Scripts/locales/bootstrap-datepicker.bs.min.js"; 
                    public const string bootstrap_datepicker_ca_min_js = "~/Scripts/locales/bootstrap-datepicker.ca.min.js"; 
                    public const string bootstrap_datepicker_cs_min_js = "~/Scripts/locales/bootstrap-datepicker.cs.min.js"; 
                    public const string bootstrap_datepicker_cy_min_js = "~/Scripts/locales/bootstrap-datepicker.cy.min.js"; 
                    public const string bootstrap_datepicker_da_min_js = "~/Scripts/locales/bootstrap-datepicker.da.min.js"; 
                    public const string bootstrap_datepicker_de_min_js = "~/Scripts/locales/bootstrap-datepicker.de.min.js"; 
                    public const string bootstrap_datepicker_el_min_js = "~/Scripts/locales/bootstrap-datepicker.el.min.js"; 
                    public const string bootstrap_datepicker_en_AU_min_js = "~/Scripts/locales/bootstrap-datepicker.en-AU.min.js"; 
                    public const string bootstrap_datepicker_en_GB_min_js = "~/Scripts/locales/bootstrap-datepicker.en-GB.min.js"; 
                    public const string bootstrap_datepicker_eo_min_js = "~/Scripts/locales/bootstrap-datepicker.eo.min.js"; 
                    public const string bootstrap_datepicker_es_min_js = "~/Scripts/locales/bootstrap-datepicker.es.min.js"; 
                    public const string bootstrap_datepicker_et_min_js = "~/Scripts/locales/bootstrap-datepicker.et.min.js"; 
                    public const string bootstrap_datepicker_eu_min_js = "~/Scripts/locales/bootstrap-datepicker.eu.min.js"; 
                    public const string bootstrap_datepicker_fa_min_js = "~/Scripts/locales/bootstrap-datepicker.fa.min.js"; 
                    public const string bootstrap_datepicker_fi_min_js = "~/Scripts/locales/bootstrap-datepicker.fi.min.js"; 
                    public const string bootstrap_datepicker_fo_min_js = "~/Scripts/locales/bootstrap-datepicker.fo.min.js"; 
                    public const string bootstrap_datepicker_fr_CH_min_js = "~/Scripts/locales/bootstrap-datepicker.fr-CH.min.js"; 
                    public const string bootstrap_datepicker_fr_min_js = "~/Scripts/locales/bootstrap-datepicker.fr.min.js"; 
                    public const string bootstrap_datepicker_gl_min_js = "~/Scripts/locales/bootstrap-datepicker.gl.min.js"; 
                    public const string bootstrap_datepicker_he_min_js = "~/Scripts/locales/bootstrap-datepicker.he.min.js"; 
                    public const string bootstrap_datepicker_hr_min_js = "~/Scripts/locales/bootstrap-datepicker.hr.min.js"; 
                    public const string bootstrap_datepicker_hu_min_js = "~/Scripts/locales/bootstrap-datepicker.hu.min.js"; 
                    public const string bootstrap_datepicker_hy_min_js = "~/Scripts/locales/bootstrap-datepicker.hy.min.js"; 
                    public const string bootstrap_datepicker_id_min_js = "~/Scripts/locales/bootstrap-datepicker.id.min.js"; 
                    public const string bootstrap_datepicker_is_min_js = "~/Scripts/locales/bootstrap-datepicker.is.min.js"; 
                    public const string bootstrap_datepicker_it_CH_min_js = "~/Scripts/locales/bootstrap-datepicker.it-CH.min.js"; 
                    public const string bootstrap_datepicker_it_min_js = "~/Scripts/locales/bootstrap-datepicker.it.min.js"; 
                    public const string bootstrap_datepicker_ja_min_js = "~/Scripts/locales/bootstrap-datepicker.ja.min.js"; 
                    public const string bootstrap_datepicker_ka_min_js = "~/Scripts/locales/bootstrap-datepicker.ka.min.js"; 
                    public const string bootstrap_datepicker_kh_min_js = "~/Scripts/locales/bootstrap-datepicker.kh.min.js"; 
                    public const string bootstrap_datepicker_kk_min_js = "~/Scripts/locales/bootstrap-datepicker.kk.min.js"; 
                    public const string bootstrap_datepicker_ko_min_js = "~/Scripts/locales/bootstrap-datepicker.ko.min.js"; 
                    public const string bootstrap_datepicker_kr_min_js = "~/Scripts/locales/bootstrap-datepicker.kr.min.js"; 
                    public const string bootstrap_datepicker_lt_min_js = "~/Scripts/locales/bootstrap-datepicker.lt.min.js"; 
                    public const string bootstrap_datepicker_lv_min_js = "~/Scripts/locales/bootstrap-datepicker.lv.min.js"; 
                    public const string bootstrap_datepicker_me_min_js = "~/Scripts/locales/bootstrap-datepicker.me.min.js"; 
                    public const string bootstrap_datepicker_mk_min_js = "~/Scripts/locales/bootstrap-datepicker.mk.min.js"; 
                    public const string bootstrap_datepicker_mn_min_js = "~/Scripts/locales/bootstrap-datepicker.mn.min.js"; 
                    public const string bootstrap_datepicker_ms_min_js = "~/Scripts/locales/bootstrap-datepicker.ms.min.js"; 
                    public const string bootstrap_datepicker_nb_min_js = "~/Scripts/locales/bootstrap-datepicker.nb.min.js"; 
                    public const string bootstrap_datepicker_nl_BE_min_js = "~/Scripts/locales/bootstrap-datepicker.nl-BE.min.js"; 
                    public const string bootstrap_datepicker_nl_min_js = "~/Scripts/locales/bootstrap-datepicker.nl.min.js"; 
                    public const string bootstrap_datepicker_no_min_js = "~/Scripts/locales/bootstrap-datepicker.no.min.js"; 
                    public const string bootstrap_datepicker_pl_min_js = "~/Scripts/locales/bootstrap-datepicker.pl.min.js"; 
                    public const string bootstrap_datepicker_pt_BR_min_js = "~/Scripts/locales/bootstrap-datepicker.pt-BR.min.js"; 
                    public const string bootstrap_datepicker_pt_min_js = "~/Scripts/locales/bootstrap-datepicker.pt.min.js"; 
                    public const string bootstrap_datepicker_ro_min_js = "~/Scripts/locales/bootstrap-datepicker.ro.min.js"; 
                    public const string bootstrap_datepicker_rs_latin_min_js = "~/Scripts/locales/bootstrap-datepicker.rs-latin.min.js"; 
                    public const string bootstrap_datepicker_rs_min_js = "~/Scripts/locales/bootstrap-datepicker.rs.min.js"; 
                    public const string bootstrap_datepicker_ru_min_js = "~/Scripts/locales/bootstrap-datepicker.ru.min.js"; 
                    public const string bootstrap_datepicker_sk_min_js = "~/Scripts/locales/bootstrap-datepicker.sk.min.js"; 
                    public const string bootstrap_datepicker_sl_min_js = "~/Scripts/locales/bootstrap-datepicker.sl.min.js"; 
                    public const string bootstrap_datepicker_sq_min_js = "~/Scripts/locales/bootstrap-datepicker.sq.min.js"; 
                    public const string bootstrap_datepicker_sr_latin_min_js = "~/Scripts/locales/bootstrap-datepicker.sr-latin.min.js"; 
                    public const string bootstrap_datepicker_sr_min_js = "~/Scripts/locales/bootstrap-datepicker.sr.min.js"; 
                    public const string bootstrap_datepicker_sv_min_js = "~/Scripts/locales/bootstrap-datepicker.sv.min.js"; 
                    public const string bootstrap_datepicker_sw_min_js = "~/Scripts/locales/bootstrap-datepicker.sw.min.js"; 
                    public const string bootstrap_datepicker_th_min_js = "~/Scripts/locales/bootstrap-datepicker.th.min.js"; 
                    public const string bootstrap_datepicker_tr_min_js = "~/Scripts/locales/bootstrap-datepicker.tr.min.js"; 
                    public const string bootstrap_datepicker_uk_min_js = "~/Scripts/locales/bootstrap-datepicker.uk.min.js"; 
                    public const string bootstrap_datepicker_vi_min_js = "~/Scripts/locales/bootstrap-datepicker.vi.min.js"; 
                    public const string bootstrap_datepicker_zh_CN_min_js = "~/Scripts/locales/bootstrap-datepicker.zh-CN.min.js"; 
                    public const string bootstrap_datepicker_zh_TW_min_js = "~/Scripts/locales/bootstrap-datepicker.zh-TW.min.js"; 
                }
            }
            public static partial class PageSpecific 
            {
                public static class Assets
                {
                }
            }
            public static partial class Shared 
            {
                public static class Assets
                {
                    public const string Logout_min_js = "~/Scripts/Shared/Logout.min.js"; 
                }
            }
            public static class Assets
            {
                public const string _references_js = "~/Scripts/_references.js"; 
                public const string bootbox_js = "~/Scripts/bootbox.js"; 
                public const string bootbox_min_js = "~/Scripts/bootbox.min.js"; 
                public const string bootstrap_3_0_1_js = "~/Scripts/bootstrap-3.0.1.js"; 
                public const string bootstrap_3_0_1_min_js = "~/Scripts/bootstrap-3.0.1.min.js"; 
                public const string bootstrap_datepicker_js = "~/Scripts/bootstrap-datepicker.js"; 
                public const string bootstrap_datepicker_min_js = "~/Scripts/bootstrap-datepicker.min.js"; 
                public const string bootstrap_js = "~/Scripts/bootstrap.js"; 
                public const string bootstrap_min_js = "~/Scripts/bootstrap.min.js"; 
                public const string jquery_2_1_3_intellisense_js = "~/Scripts/jquery-2.1.3.intellisense.js"; 
                public const string jquery_2_1_3_js = "~/Scripts/jquery-2.1.3.js"; 
                public const string jquery_2_1_3_min_js = "~/Scripts/jquery-2.1.3.min.js"; 
                public const string jquery_2_2_1_js = "~/Scripts/jquery-2.2.1.js"; 
                public const string jquery_2_2_1_min_js = "~/Scripts/jquery-2.2.1.min.js"; 
                public const string jquery_ui_1_11_2_js = "~/Scripts/jquery-ui-1.11.2.js"; 
                public const string jquery_ui_1_11_2_min_js = "~/Scripts/jquery-ui-1.11.2.min.js"; 
                public const string jquery_ui_1_11_3_js = "~/Scripts/jquery-ui-1.11.3.js"; 
                public const string jquery_ui_1_11_3_min_js = "~/Scripts/jquery-ui-1.11.3.min.js"; 
                public const string jquery_ui_1_11_4_js = "~/Scripts/jquery-ui-1.11.4.js"; 
                public const string jquery_ui_1_11_4_min_js = "~/Scripts/jquery-ui-1.11.4.min.js"; 
                public const string jquery_mobile_1_4_5_js = "~/Scripts/jquery.mobile-1.4.5.js"; 
                public const string jquery_mobile_1_4_5_min_js = "~/Scripts/jquery.mobile-1.4.5.min.js"; 
                public const string jquery_validate_js = "~/Scripts/jquery.validate.js"; 
                public const string jquery_validate_min_js = "~/Scripts/jquery.validate.min.js"; 
                public const string jquery_validate_unobtrusive_js = "~/Scripts/jquery.validate.unobtrusive.js"; 
                public const string jquery_validate_unobtrusive_min_js = "~/Scripts/jquery.validate.unobtrusive.min.js"; 
                public const string modernizr_2_6_2_js = "~/Scripts/modernizr-2.6.2.js"; 
                public const string modernizr_2_7_2_js = "~/Scripts/modernizr-2.7.2.js"; 
                public const string modernizr_2_8_3_js = "~/Scripts/modernizr-2.8.3.js"; 
                public const string Namespace_js = "~/Scripts/Namespace.js"; 
                public const string respond_js = "~/Scripts/respond.js"; 
                public const string respond_matchmedia_addListener_js = "~/Scripts/respond.matchmedia.addListener.js"; 
                public const string respond_matchmedia_addListener_min_js = "~/Scripts/respond.matchmedia.addListener.min.js"; 
                public const string respond_min_js = "~/Scripts/respond.min.js"; 
                public const string toastr_js = "~/Scripts/toastr.js"; 
                public const string toastr_min_js = "~/Scripts/toastr.min.js"; 
            }
        }
        public static partial class Content 
        {
            public static partial class Images 
            {
                public static partial class icons_png 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class icons_svg 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class Sass 
            {
                public static class Assets
                {
                }
            }
            public static partial class themes 
            {
                public static partial class @base 
                {
                    public static partial class images 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                        public const string accordion_css = "~/Content/themes/base/accordion.css";
                        public const string all_css = "~/Content/themes/base/all.css";
                        public const string autocomplete_css = "~/Content/themes/base/autocomplete.css";
                        public const string base_css = "~/Content/themes/base/base.css";
                        public const string button_css = "~/Content/themes/base/button.css";
                        public const string core_css = "~/Content/themes/base/core.css";
                        public const string datepicker_css = "~/Content/themes/base/datepicker.css";
                        public const string dialog_css = "~/Content/themes/base/dialog.css";
                        public const string draggable_css = "~/Content/themes/base/draggable.css";
                        public const string menu_css = "~/Content/themes/base/menu.css";
                        public const string progressbar_css = "~/Content/themes/base/progressbar.css";
                        public const string resizable_css = "~/Content/themes/base/resizable.css";
                        public const string selectable_css = "~/Content/themes/base/selectable.css";
                        public const string selectmenu_css = "~/Content/themes/base/selectmenu.css";
                        public const string slider_css = "~/Content/themes/base/slider.css";
                        public const string sortable_css = "~/Content/themes/base/sortable.css";
                        public const string spinner_css = "~/Content/themes/base/spinner.css";
                        public const string tabs_css = "~/Content/themes/base/tabs.css";
                        public const string theme_css = "~/Content/themes/base/theme.css";
                        public const string tooltip_css = "~/Content/themes/base/tooltip.css";
                    }
                }
                public static partial class Hydrogen 
                {
                    public static class Assets
                    {
                        public const string animate_css = "~/Content/themes/Hydrogen/animate.css";
                        public const string icomoon_css = "~/Content/themes/Hydrogen/icomoon.css";
                        public const string magnific_popup_css = "~/Content/themes/Hydrogen/magnific-popup.css";
                        public const string salvattore_css = "~/Content/themes/Hydrogen/salvattore.css";
                        public const string style_css = "~/Content/themes/Hydrogen/style.css";
                    }
                }
                public static class Assets
                {
                }
            }
            public static class Assets
            {
                public const string bootstrap_datepicker_css = "~/Content/bootstrap-datepicker.css";
                public const string bootstrap_datepicker_min_css = "~/Content/bootstrap-datepicker.min.css";
                public const string bootstrap_datepicker_standalone_css = "~/Content/bootstrap-datepicker.standalone.css";
                public const string bootstrap_datepicker_standalone_min_css = "~/Content/bootstrap-datepicker.standalone.min.css";
                public const string bootstrap_datepicker3_css = "~/Content/bootstrap-datepicker3.css";
                public const string bootstrap_datepicker3_min_css = "~/Content/bootstrap-datepicker3.min.css";
                public const string bootstrap_datepicker3_standalone_css = "~/Content/bootstrap-datepicker3.standalone.css";
                public const string bootstrap_datepicker3_standalone_min_css = "~/Content/bootstrap-datepicker3.standalone.min.css";
                public const string bootstrap_css = "~/Content/bootstrap.css";
                public const string bootstrap_min_css = "~/Content/bootstrap.min.css";
                public const string font_awesome_css = "~/Content/font-awesome.css";
                public const string font_awesome_min_css = "~/Content/font-awesome.min.css";
                public const string jquery_mobile_1_4_5_css = "~/Content/jquery.mobile-1.4.5.css";
                public const string jquery_mobile_1_4_5_min_css = "~/Content/jquery.mobile-1.4.5.min.css";
                public const string jquery_mobile_external_png_1_4_5_css = "~/Content/jquery.mobile.external-png-1.4.5.css";
                public const string jquery_mobile_external_png_1_4_5_min_css = "~/Content/jquery.mobile.external-png-1.4.5.min.css";
                public const string jquery_mobile_icons_1_4_5_css = "~/Content/jquery.mobile.icons-1.4.5.css";
                public const string jquery_mobile_icons_1_4_5_min_css = "~/Content/jquery.mobile.icons-1.4.5.min.css";
                public const string jquery_mobile_inline_png_1_4_5_css = "~/Content/jquery.mobile.inline-png-1.4.5.css";
                public const string jquery_mobile_inline_png_1_4_5_min_css = "~/Content/jquery.mobile.inline-png-1.4.5.min.css";
                public const string jquery_mobile_inline_svg_1_4_5_css = "~/Content/jquery.mobile.inline-svg-1.4.5.css";
                public const string jquery_mobile_inline_svg_1_4_5_min_css = "~/Content/jquery.mobile.inline-svg-1.4.5.min.css";
                public const string jquery_mobile_structure_1_4_5_css = "~/Content/jquery.mobile.structure-1.4.5.css";
                public const string jquery_mobile_structure_1_4_5_min_css = "~/Content/jquery.mobile.structure-1.4.5.min.css";
                public const string jquery_mobile_theme_1_4_5_css = "~/Content/jquery.mobile.theme-1.4.5.css";
                public const string jquery_mobile_theme_1_4_5_min_css = "~/Content/jquery.mobile.theme-1.4.5.min.css";
                public const string Responsive_css = "~/Content/Responsive.css";
                public const string Site_css = "~/Content/Site.css";
                public const string toastr_css = "~/Content/toastr.css";
                public const string toastr_min_css = "~/Content/toastr.min.css";
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


