// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class movienowinheritsfrombaseitem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(movienowinheritsfrombaseitem));
        
        string IMigrationMetadata.Id
        {
            get { return "201606140048456_movie now inherits from base item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
