// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Madedirectorrequiredformovies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Madedirectorrequiredformovies));
        
        string IMigrationMetadata.Id
        {
            get { return "201608100056576_Made director required for movies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
