// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedcompletedtoownedforwish : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedcompletedtoownedforwish));
        
        string IMigrationMetadata.Id
        {
            get { return "201703161622223_changed completed to owned for wish"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
